### ISSUE TITLE
출력되는 RSS 갯수가 너무 많습니다

### ISSUE THREAD

**Issue by item4** [spoqa/spoqa.github.com#130]
[소스를 보아하니](https://github.com/spoqa/spoqa.github.com/blob/master/atom.xml#L18) 갯수 제한 없이 모든 포스트를 출력하는걸로 보입니다.

지금 RSS reader를 세팅하다 본 것인데, 리더에 순식간에 62개의 읽지 않은 글이 생겨버립니다.

갈수록 갯수가 많아질텐데 갯수를 제한해두는게 좋지 않을까요?

**Comment by item4** [comment]
<img width="248" alt="2015-10-14 8 50 42" src="https://cloud.githubusercontent.com/assets/559952/10482711/46bd4c1e-72b5-11e5-9fd0-3391b7189bdd.png">

처음 불러오기를 하면 이렇게 됩니다..

**Comment by shinvee** [comment]
의견 주셔서 감사합니다. 처음 만들 때 이렇게 많이 글을 쓸 때까지 살아있을 줄 생각 못하고...
최신 20개정도로 조정하도록 하겠습니다. :)
