### ISSUE TITLE
취소선 마크업이 제대로 안 된 게시물이 있습니다

### ISSUE THREAD

**Issue by item4** [spoqa/spoqa.github.com#134]
[포토샵 플러그인 살펴보기 (1)](http://spoqa.github.io/2014/05/19/photoshop-plugin-1.html)

`~~ 취소선 마크업 ~~`이 안된 부분들이 보입니다.

**Comment by admire93** [comment]
깃헙 페이지에서 사용하는 마크업 엔진이 바뀌면서 해결된듯합니다.
