### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by keon** [spoqa/spoqa.github.com#187]
안녕하세요! 블로그 템플릿이 마음에 들어서 사용하고싶은데 라이센스 정보가 없어서 여기다가 문의드립니다.
폰트, 사진, 글 등은 모두 지우고 제킬 템플릿만 이용하고 싶습니다.

**Comment by young-hwa** [comment]
안녕하세요. 
먼저 저희 블로그에 관심가져주셔서 감사합니다.
저희 블로그 템플릿은 저작권은 스포카에 귀속되어있으므로 따로 템플릿 이용이 불가능합니다.
라이선스 정보는 블로그 하단에 아래와 같이 적혀있으니 참고 부탁드립니다.

> ©Spoqa Inc. All rights reserved.

감사합니다.
