### ISSUE TITLE
"spoqa.github.io/job" has been moved to "spoqa.github.io/jobs"

### ISSUE THREAD

**Issue by simnalamburt** [spoqa/spoqa.github.com#224]
The Easter egg link of dodopoint.com has been moved from "spoqa.github.io/job" to "spoqa.github.io/jobs". Thanks!

<img width="421" alt="2017-10-18 2 05 50" src="https://user-images.githubusercontent.com/4435445/31701811-d62b6624-b40d-11e7-9e64-bdbf96c1690f.png">

**Comment by dahlia** [comment]
Now fixed. Thanks!
