### ISSUE TITLE
프로필 업데이트

### ISSUE THREAD

**Issue by sairion** [spoqa/spoqa.github.com#94]
soo kang pi ed huui 님의 프로필 업데이트가 필요할 것 같네요. (edit)

**Comment by admire93** [comment]
저도해야되겠군요.

**Comment by young-hwa** [comment]
gracie님도 없군요

**Comment by admire93** [comment]
- soo
- ed 
추가 되었고

- gracie
- pi
- kang
- huui

남았습니다

**Comment by young-hwa** [comment]
are님 포함 전부 다 추가 했으므로 이슈를 닫겠습니다.
