### ISSUE TITLE
RSS를 발행해주세요

### ISSUE THREAD

**Issue by item4** [spoqa/spoqa.github.com#96]
새 글 알림을 받아보고 싶습니다. RSS를 주세요 (__ )

**Comment by dahlia** [comment]
이미 [Atom 피드][1]에 대한 auto discovery 선언이 HTML 헤더에 되어 있습니다:

```html
<link href="./atom.xml" type="application/atom+xml" rel="alternate" title="Spoqa Tech Blog" />
```

[1]: http://spoqa.github.io/atom.xml
